# Actual v2 QML components, flattened exactly as the v2 resource module.
# Regenerate with scripts/build/mobile-qml-closure.py.
set(MOBILE_V2_QML_FILES
    "${PROJECT_SOURCE_DIR}/src/app/ui/sidebar/ActivityBar.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/preferences/AppBackgroundPage.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/components/AppButton.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/components/AppCheckBox.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/components/AppComboBox.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/components/AppDialog.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/components/AppDropDownButton.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/components/AppDropdownPanel.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/components/AppMenu.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/components/AppMenuAction.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/components/AppMenuItem.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/components/AppMenuSeparator.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/components/AppScrollBar.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/components/AppSlider.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/components/AppStickyPopup.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/components/AppSwitch.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/components/AppTab.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/components/AppTextArea.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/components/AppTextField.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/preferences/ApplicationBackground.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/preview/AudioSettingsDialog.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/components/BackdropBlur.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/timeline/BottomPanel.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/timeline/BottomTabBar.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/sidebar/ChartFieldSidebar.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/components/ChoiceDialog.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/components/ChromeRow.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/editor/CompletionPopup.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/export/CoverBatchExportDialog.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/export/CoverExportPage.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/editor/DesignerSlotsDialog.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/components/DialogFooter.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/sidebar/DifficultyList.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/components/DifficultySwatch.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/components/EditableValue.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/editor/EditorPane.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/editor/EditorPointerArea.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/editor/EditorTabBar.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/export/ExportRangeSelector.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/sidebar/ExportSidebarPage.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/export/ExportVideoPage.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/components/FadeTransition.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/editor/FindReplaceBar.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/components/FloatingCard.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/components/HoverChrome.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/components/IconButton.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/components/ImageSequence.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/components/JobProgressOverlay.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/components/LabeledCombo.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/components/LabeledSlider.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/latency/LatencyPage.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/editor/LineNumberGutter.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/chrome/MainMenu.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/chrome/MainMenuCommands.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/chrome/MainToolBar.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/components/NavRow.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/editor/NormalizeOptionsDialog.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/preview/NoteStatistics.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/components/PanelHeader.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/preferences/PreferencesDialog.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/preview/PreviewAppearancePages.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/preview/PreviewCanvasMenu.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/preview/PreviewPane.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/preview/PreviewRateMenu.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/preview/PreviewRateToast.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/preview/PreviewRenderModeMenu.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/preview/PreviewSettingsDialog.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/preview/PreviewTransport.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/components/SettingsSection.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/chrome/ShortcutBindings.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/editor/SourceEditor.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/components/SplitHandle.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/chrome/StatusBar.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/theme/Theme.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/timeline/TimelineBrightnessMenu.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/timeline/TimelineZoomMenu.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/components/Tooltip.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/components/UiRequestHost.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/ViewState.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/layout/WelcomePage.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/chrome/WindowCaptionButtons.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/chrome/WindowGestureArea.qml"
    "${PROJECT_SOURCE_DIR}/src/app/ui/chrome/WindowTitleBar.qml"
)
foreach(qml IN LISTS MOBILE_V2_QML_FILES)
    get_filename_component(name "${qml}" NAME)
    set_source_files_properties("${qml}" PROPERTIES QT_RESOURCE_ALIAS "${name}")
endforeach()
set_source_files_properties("${PROJECT_SOURCE_DIR}/src/app/ui/theme/Theme.qml" PROPERTIES QT_QML_SINGLETON_TYPE TRUE)
file(GLOB MOBILE_V2_ICONS "${PROJECT_SOURCE_DIR}/src/app/ui/resources/icons/*")
foreach(icon IN LISTS MOBILE_V2_ICONS)
    get_filename_component(name "${icon}" NAME)
    set_source_files_properties("${icon}" PROPERTIES QT_RESOURCE_ALIAS "icons/${name}")
endforeach()
