// Generated by scripts/api/generate_net_api.py. Do not edit.
// This defines the API contract; availability is determined by the connected host.
export type EmptyRequest = {  };
export type OpaqueRef = string;
export type Uint64 = string;
export type Error = { "code": string; "message": string; "retryable": boolean; "upstreamStatus"?: number; "retryAfterMs"?: number; "diagnosticId"?: string; "field"?: string; [key: string]: unknown };
export type ProviderRequest = { "providerId": string };
export type ChartQueryRequest = { "providerId": string; "uploader"?: string; "tag"?: string; "title"?: string; "startDate"?: string; "endDate"?: string; "timeZone"?: string; "caseSensitive"?: boolean; "forceRefresh"?: boolean; "sort"?: "level_asc" | "level_desc" | "uploaded_asc" | "uploaded_desc" | "title_asc" | "title_desc" };
export type QueryPageRequest = { "queryRef": string; "limit"?: number; "cursor"?: string };
export type Destination = { "kind": "managed" } | { "kind": "directory_grant"; "grantRef": string };
export type DownloadRequest = { "providerId": string; "chartIds": Array<string>; "destination": Destination; "includeVideo"?: boolean; "createZip"?: boolean; "zipMode"?: "downloaded_resources" | "legacy_triplet"; "conflictPolicy"?: "fail" | "replace"; "emptyChartPolicy"?: "allow_declared_empty" | "reject" };
export type ScanRequest = { "rootGrantRef": string; "depth"?: 1; "uploadPlanRef"?: OpaqueRef; "retainedItemIds"?: Array<OpaqueRef> };
export type UploadRequest = { "uploadPlanRef": string; "orderedItemIds": Array<string>; "accountRef": string; "parentJobId"?: OpaqueRef };
export type AccountLoginRequest = { "providerId": string; "username": string; "password": string; "remember"?: boolean };
export type AccountRefRequest = { "accountRef": string };
export type PreviewPrepareRequest = { "providerId": string; "chartId": string; "remoteVersion"?: string; "forceRefresh"?: boolean };
export type PreviewOpenRequest = { "previewRef": string; "expectedWorkspaceId": string; "expectedDocumentOpenGeneration": string; "expectedRevision": string };
export type PreviewRefRequest = { "previewRef": string };
export type NetSettingsPatch = { "includeVideo"?: boolean; "createZip"?: boolean; "zipMode"?: "downloaded_resources" | "legacy_triplet"; "caseSensitive"?: boolean; "sort"?: "level_asc" | "level_desc" | "uploaded_asc" | "uploaded_desc" | "title_asc" | "title_desc"; "timeZone"?: string; "destination"?: Destination };
export type NetSettings = { "includeVideo": boolean; "createZip": boolean; "zipMode": "downloaded_resources" | "legacy_triplet"; "caseSensitive": boolean; "sort": "level_asc" | "level_desc" | "uploaded_asc" | "uploaded_desc" | "title_asc" | "title_desc"; "timeZone": string; "destination": Destination; "directoryDisplayName"?: string; [key: string]: unknown };
export type JobListRequest = { "limit"?: number; "cursor"?: string; "kind"?: string; "state"?: "queued" | "running" | "retry_wait" | "awaiting_user" | "blocked" | "cancelling" | "succeeded" | "partial" | "failed" | "cancelled" };
export type JobRefRequest = { "jobId": string };
export type ItemPageRequest = { "jobId": string; "limit"?: number; "cursor"?: string };
export type EventPageRequest = { "jobId": string; "after"?: string; "limit"?: number };
export type ResumeRequest = { "jobId": string; "expectedJobVersion": string; "reason": string };
export type RetryRequest = { "jobId": string; "itemIds": Array<string>; "reason": string };
export type FileGrantRequest = { "purpose": "upload_read" | "download_write" | "export_read"; "selectFolder"?: true };
export type ArtifactRefRequest = { "artifactRef": string };
export type TargetGrantRequest = { "scheme": "https" | "http"; "host": string; "port": number; "addressClass"?: "public" | "loopback" | "private"; "methods"?: Array<"GET">; "purpose": string };
export type HttpFetchRequest = { "url": string; "targetGrantRef": string; "timeoutMs"?: number };
export type HttpDownloadRequest = { "url": string; "targetGrantRef": string; "timeoutMs"?: number; "destination": Destination };
export type ProxyRefRequest = { "profileId": "net" | "generic-http" | "update" };
export type ProxyProfileRequest = { "profileId": "net" | "generic-http" | "update"; "mode": "system" | "direct" | "http_connect" | "socks5"; "host"?: string; "port"?: number; "credentialMode"?: "none" | "existing" | "prompt"; "credentialRef"?: string };
export type PairingRequest = { "clientName": string; "requestedScopes": Array<string> };
export type PairingExchangeRequest = { "pairingRef": string; "clientSecret": string };
export type JobHandle = { "jobId": string; "kind": string; "state": "queued" | "running" | "retry_wait" | "awaiting_user" | "blocked" | "cancelling" | "succeeded" | "partial" | "failed" | "cancelled"; "parentJobId"?: string; [key: string]: unknown };
export type Progress = { "bytesReceived": string; "bytesTotal": Uint64 | null; [key: string]: unknown };
export type Counts = { "total": number; "succeeded": number; "failed": number; "pending": number; "cancelled": number; "skipped": number; "unknown": number; [key: string]: unknown };
export type JobSnapshot = { "jobId": string; "kind": string; "state": "queued" | "running" | "retry_wait" | "awaiting_user" | "blocked" | "cancelling" | "succeeded" | "partial" | "failed" | "cancelled"; "parentJobId"?: string; "phase": string; "version": string; "sequence": string; "createdAt": string; "updatedAt": string; "counts": Counts; "progress": Progress; "result": unknown; "error": Error | null; [key: string]: unknown };
export type ArtifactDescriptor = { "artifactRef": string; "displayName": string; "contentType": string | null; "bytes": Uint64 | null; "expiresAt": string; "kind": "file" | "directory"; [key: string]: unknown };
export type ItemSnapshot = { "itemId": string; "inputOrder": number; "parentItemId"?: string; "chartRef"?: string; "materialRef"?: string; "state": "pending" | "running" | "retry_wait" | "blocked" | "succeeded" | "failed" | "cancelled" | "skipped" | "outcome_unknown"; "phase": string; "attempt": number; "bytesReceived": string; "bytesTotal": Uint64 | null; "error": Error | null; "artifacts": Array<ArtifactDescriptor>; "retryAt"?: string | null; [key: string]: unknown };
export type JobEvent = { "jobId": string; "itemId"?: string; "sequence": string; "type": "job.updated" | "item.updated" | "job.completed"; "at": string; "payload": JobSnapshot; "item"?: ItemSnapshot; [key: string]: unknown };
export type JobPage = { "items": Array<JobSnapshot>; "nextCursor": string | null; [key: string]: unknown };
export type ItemPage = { "jobId": string; "items": Array<ItemSnapshot>; "nextCursor": string | null; "snapshotVersion": string; [key: string]: unknown };
export type EventPage = { "events": Array<JobEvent>; "nextAfter": string; "snapshotVersion": string; [key: string]: unknown };
export type ProbeResult = { "classification": "normal" | "slow"; "elapsedMs": number; "upstreamStatus": number; [key: string]: unknown };
export type QueryHandle = { "queryRef": string; "matchedCount": number; "skippedRows": number; "completeness": "unknown"; "expiresAt": string; [key: string]: unknown };
export type ChartSummary = { "providerId": string; "chartId": string; "title": string; "artist": string; "designer": string; "uploader": string; "levels": Array<string>; "tags": Array<string>; "uploadedAtUtc": string; "remoteVersion": string | null; [key: string]: unknown };
export type ChartPage = { "queryRef": string; "items": Array<ChartSummary>; "nextCursor": string | null; "matchedCount": number; "completeness": "unknown"; [key: string]: unknown };
export type ProviderDescriptor = { "providerId": string; "protocolVersion": string; "supportedOperations": Array<string>; "resources": Array<"chart" | "track" | "image" | "video">; "requiresAccount": boolean; "limits": { [key: string]: unknown }; "available": boolean; "reason"?: string; [key: string]: unknown };
export type ProviderList = Array<ProviderDescriptor>;
export type OperationCapability = { "id": string; "available": boolean; "reason": string | null; "scopes": { "allOf": Array<string>; "anyOf": Array<string>; [key: string]: unknown }; "schemaVersion": string; "adapters": { "internal": boolean; "http": boolean; "cli": boolean; [key: string]: unknown }; [key: string]: unknown };
export type CapabilitySet = { "apiVersion": "1.0"; "hostInstanceId": string; "applicationVersion": string; "platform": string; "timeZone": string; "operations": Array<OperationCapability>; "limits": { "controlRequestBytes": number; "batchItems": number; "pageItems": number; "jobRecordRetention": string; [key: string]: unknown }; [key: string]: unknown };
export type AccountDescriptor = { "accountRef": string; "providerId": string; "displayName": string; "authenticated": boolean; "expiresAt": string | null; "remembered": boolean; [key: string]: unknown };
export type AccountList = Array<AccountDescriptor>;
export type ReleaseResult = { "released": boolean; [key: string]: unknown };
export type DocumentIdentity = { "workspaceId": string; "documentOpenGeneration": string; "revision": string; "dirty": boolean; "hasDocument": boolean; "origin": "local" | "net_preview"; [key: string]: unknown };
export type ResourceEntry = { "kind": "chart" | "track" | "image" | "video"; "state": "present" | "absent" | "failed"; "artifactRef"?: string; "relativeName"?: string; "bytes"?: string; "contentType"?: string; "sha256"?: string; "acceptedDeclaredEmpty"?: boolean; "error"?: Error; [key: string]: unknown };
export type ResourceManifest = { "providerId": string; "chartId": string; "remoteVersion": string | null; "resources": Array<ResourceEntry>; [key: string]: unknown };
export type DownloadBatchResult = { "manifests": Array<ResourceManifest>; "itemIds": Array<string>; "counts": Counts; "directoryArtifacts": Array<ArtifactDescriptor>; "zipArtifacts"?: Array<ArtifactDescriptor>; [key: string]: unknown };
export type UploadMaterial = { "itemId": string; "displayName": string; "materialRef": string; "files": Array<{ "kind": "chart" | "track" | "image" | "video"; "displayName": string; "bytes": string; "modifiedAt": string; "sha256"?: string; [key: string]: unknown }>; [key: string]: unknown };
export type UploadPlan = { "uploadPlanRef": string; "items": Array<UploadMaterial>; "rejectedEntries": Array<{ "displayName": string; "reason": string; [key: string]: unknown }>; "expiresAt": string; [key: string]: unknown };
export type UploadBatchResult = { "accountRef": string; "completedItemIds": Array<string>; "unknownItemIds": Array<string>; "itemIds": Array<string>; "counts": Counts; "receipts": Array<{ "itemId": string; "chartId"?: string; "remoteVersion"?: string; "status": number; [key: string]: unknown }>; [key: string]: unknown };
export type PreviewHandle = { "previewRef": string; "manifest": ResourceManifest; "expiresAt": string; [key: string]: unknown };
export type PreviewOpenResult = { "previewRef": string; "document": DocumentIdentity; [key: string]: unknown };
export type FileGrant = { "grantRef": string; "purpose": "upload_read" | "download_write" | "export_read"; "displayName": string; "expiresAt": string; "allowOverwrite": boolean; [key: string]: unknown };
export type TargetGrant = { "targetGrantRef": string; "scheme": "http" | "https"; "host": string; "port": number; "addressClass": "public" | "loopback" | "private"; "methods": Array<"GET">; "expiresAt": string; [key: string]: unknown };
export type HttpTextResult = { "status": number; "contentType": string; "text": string; "bytes": string; [key: string]: unknown };
export type ArtifactManifest = { "artifact": ArtifactDescriptor; "integrity": { "sha256"?: string; [key: string]: unknown } | null; "source": { "status": number; "contentType": string; "receivedAt": string; [key: string]: unknown }; [key: string]: unknown };
export type HttpDownloadResult = { "manifest": ArtifactManifest; "artifactRef": string; "status": number; [key: string]: unknown };
export type ProxyProfile = { "profileId": "net" | "generic-http" | "update"; "mode": "system" | "direct" | "http_connect" | "socks5"; "host"?: string; "port"?: number; "credentialMode": "none" | "existing" | "prompt"; "hasCredential": boolean; "readOnly": boolean; [key: string]: unknown };
export type DiagnosticSummary = { "jobId": string; "diagnosticId": string; "entries": Array<{ "at": string; "code": string; "message": string; "itemId"?: string; [key: string]: unknown }>; "truncated": boolean; [key: string]: unknown };
export type PairingChallenge = { "pairingRef": string; "clientSecret": string; "expiresAt": string; [key: string]: unknown };
export type PairingResult = { "principalId": string; "token": string; "expiresAt": string; "grantedScopes": Array<string>; [key: string]: unknown };
export type BinaryContent = string;
export type InheritedJobResult = unknown;
export interface OperationMap {
  "api.capabilities": { request: EmptyRequest; result: CapabilitySet };
  "net.providers.list": { request: EmptyRequest; result: ProviderList };
  "net.probes.create": { request: ProviderRequest; result: JobHandle };
  "net.queries.create": { request: ChartQueryRequest; result: JobHandle };
  "net.queries.results": { request: QueryPageRequest; result: ChartPage };
  "net.downloads.create": { request: DownloadRequest; result: JobHandle };
  "net.uploads.scan": { request: ScanRequest; result: JobHandle };
  "net.uploads.create": { request: UploadRequest; result: JobHandle };
  "net.accounts.login": { request: AccountLoginRequest; result: JobHandle };
  "net.accounts.list": { request: EmptyRequest; result: AccountList };
  "net.accounts.logout": { request: AccountRefRequest; result: ReleaseResult };
  "net.previews.prepare": { request: PreviewPrepareRequest; result: JobHandle };
  "net.previews.open": { request: PreviewOpenRequest; result: JobHandle };
  "net.previews.release": { request: PreviewRefRequest; result: ReleaseResult };
  "document.snapshot": { request: EmptyRequest; result: DocumentIdentity };
  "net.settings.get": { request: EmptyRequest; result: NetSettings };
  "net.settings.update": { request: NetSettingsPatch; result: NetSettings };
  "jobs.list": { request: JobListRequest; result: JobPage };
  "jobs.get": { request: JobRefRequest; result: JobSnapshot };
  "jobs.items": { request: ItemPageRequest; result: ItemPage };
  "jobs.events": { request: EventPageRequest; result: EventPage };
  "jobs.cancel": { request: JobRefRequest; result: JobSnapshot };
  "jobs.resume": { request: ResumeRequest; result: JobSnapshot };
  "jobs.retry": { request: RetryRequest; result: JobHandle };
  "jobs.diagnostics": { request: JobRefRequest; result: DiagnosticSummary };
  "files.grants.request": { request: FileGrantRequest; result: JobHandle };
  "files.artifacts.content": { request: ArtifactRefRequest; result: ArrayBuffer };
  "network.targets.request": { request: TargetGrantRequest; result: JobHandle };
  "network.http.fetch": { request: HttpFetchRequest; result: JobHandle };
  "network.http.download": { request: HttpDownloadRequest; result: JobHandle };
  "network.proxy.get": { request: ProxyRefRequest; result: ProxyProfile };
  "network.proxy.set": { request: ProxyProfileRequest; result: JobHandle };
  "gateway.pairings.create": { request: PairingRequest; result: PairingChallenge };
  "gateway.pairings.exchange": { request: PairingExchangeRequest; result: PairingResult };
}
export type OperationId = keyof OperationMap;
export const operations = {
  "api.capabilities": {"method":"GET","path":"/capabilities","async":false,"idempotency":"natural","adapters":{"internal":true,"http":false,"cli":false},"binary":false},
  "net.providers.list": {"method":"GET","path":"/net/providers","async":false,"idempotency":"natural","adapters":{"internal":true,"http":false,"cli":false},"binary":false},
  "net.probes.create": {"method":"POST","path":"/net/probes","async":true,"idempotency":"optional","adapters":{"internal":true,"http":false,"cli":false},"binary":false},
  "net.queries.create": {"method":"POST","path":"/net/queries","async":true,"idempotency":"optional","adapters":{"internal":true,"http":false,"cli":false},"binary":false},
  "net.queries.results": {"method":"GET","path":"/net/queries/{queryRef}","async":false,"idempotency":"natural","adapters":{"internal":true,"http":false,"cli":false},"binary":false},
  "net.downloads.create": {"method":"POST","path":"/net/downloads","async":true,"idempotency":"required","adapters":{"internal":true,"http":false,"cli":false},"binary":false},
  "net.uploads.scan": {"method":"POST","path":"/net/upload-plans","async":true,"idempotency":"optional","adapters":{"internal":true,"http":false,"cli":false},"binary":false},
  "net.uploads.create": {"method":"POST","path":"/net/uploads","async":true,"idempotency":"required","adapters":{"internal":true,"http":false,"cli":false},"binary":false},
  "net.accounts.login": {"method":"POST","path":"/net/accounts","async":true,"idempotency":"none","adapters":{"internal":true,"http":false,"cli":false},"binary":false},
  "net.accounts.list": {"method":"GET","path":"/net/accounts","async":false,"idempotency":"natural","adapters":{"internal":true,"http":false,"cli":false},"binary":false},
  "net.accounts.logout": {"method":"DELETE","path":"/net/accounts/{accountRef}","async":false,"idempotency":"natural","adapters":{"internal":true,"http":false,"cli":false},"binary":false},
  "net.previews.prepare": {"method":"POST","path":"/net/previews","async":true,"idempotency":"optional","adapters":{"internal":true,"http":false,"cli":false},"binary":false},
  "net.previews.open": {"method":"POST","path":"/net/previews/{previewRef}/open","async":true,"idempotency":"required","adapters":{"internal":true,"http":false,"cli":false},"binary":false},
  "net.previews.release": {"method":"DELETE","path":"/net/previews/{previewRef}","async":false,"idempotency":"natural","adapters":{"internal":true,"http":false,"cli":false},"binary":false},
  "document.snapshot": {"method":"GET","path":"/document/snapshot","async":false,"idempotency":"natural","adapters":{"internal":true,"http":false,"cli":false},"binary":false},
  "net.settings.get": {"method":"GET","path":"/net/settings","async":false,"idempotency":"natural","adapters":{"internal":false,"http":false,"cli":false},"binary":false},
  "net.settings.update": {"method":"PATCH","path":"/net/settings","async":false,"idempotency":"natural","adapters":{"internal":false,"http":false,"cli":false},"binary":false},
  "jobs.list": {"method":"GET","path":"/jobs","async":false,"idempotency":"natural","adapters":{"internal":true,"http":false,"cli":false},"binary":false},
  "jobs.get": {"method":"GET","path":"/jobs/{jobId}","async":false,"idempotency":"natural","adapters":{"internal":true,"http":false,"cli":false},"binary":false},
  "jobs.items": {"method":"GET","path":"/jobs/{jobId}/items","async":false,"idempotency":"natural","adapters":{"internal":true,"http":false,"cli":false},"binary":false},
  "jobs.events": {"method":"GET","path":"/jobs/{jobId}/events","async":false,"idempotency":"natural","adapters":{"internal":true,"http":false,"cli":false},"binary":false},
  "jobs.cancel": {"method":"POST","path":"/jobs/{jobId}/cancel","async":false,"idempotency":"natural","adapters":{"internal":true,"http":false,"cli":false},"binary":false},
  "jobs.resume": {"method":"POST","path":"/jobs/{jobId}/resume","async":false,"idempotency":"required","adapters":{"internal":false,"http":false,"cli":false},"binary":false},
  "jobs.retry": {"method":"POST","path":"/jobs/{jobId}/retry","async":true,"idempotency":"required","adapters":{"internal":false,"http":false,"cli":false},"binary":false},
  "jobs.diagnostics": {"method":"GET","path":"/jobs/{jobId}/diagnostics","async":false,"idempotency":"natural","adapters":{"internal":false,"http":false,"cli":false},"binary":false},
  "files.grants.request": {"method":"POST","path":"/files/grants","async":true,"idempotency":"optional","adapters":{"internal":false,"http":false,"cli":false},"binary":false},
  "files.artifacts.content": {"method":"GET","path":"/files/artifacts/{artifactRef}/content","async":false,"idempotency":"natural","adapters":{"internal":false,"http":false,"cli":false},"binary":true},
  "network.targets.request": {"method":"POST","path":"/network/target-grants","async":true,"idempotency":"optional","adapters":{"internal":false,"http":false,"cli":false},"binary":false},
  "network.http.fetch": {"method":"POST","path":"/network/fetch","async":true,"idempotency":"optional","adapters":{"internal":false,"http":false,"cli":false},"binary":false},
  "network.http.download": {"method":"POST","path":"/network/downloads","async":true,"idempotency":"required","adapters":{"internal":false,"http":false,"cli":false},"binary":false},
  "network.proxy.get": {"method":"GET","path":"/network/proxy/{profileId}","async":false,"idempotency":"natural","adapters":{"internal":false,"http":false,"cli":false},"binary":false},
  "network.proxy.set": {"method":"PUT","path":"/network/proxy/{profileId}","async":true,"idempotency":"optional","adapters":{"internal":false,"http":false,"cli":false},"binary":false},
  "gateway.pairings.create": {"method":"POST","path":"/pairings","async":false,"idempotency":"none","adapters":{"internal":false,"http":false,"cli":false},"binary":false},
  "gateway.pairings.exchange": {"method":"POST","path":"/pairings/{pairingRef}/exchange","async":false,"idempotency":"none","adapters":{"internal":false,"http":false,"cli":false},"binary":false},
} as const;
